### ISSUE TITLE
How to add stones to board prior to the first move?

### ISSUE THREAD

**Issue by horaceho** [db3108/michi-c#2]
Is there a suggested way to add stones to the board?

For example, currently I add two black stones to board by:

```
$ ./michi gtp
play black c3
Move: 1     Black: 0 caps   White: 0 caps   Komi: 7.5
 13 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 12 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 11 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 10 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 9  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 8  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 7  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 6  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 5  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 4  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 3  . .(X). . . . . . . . . .     . . . . . . . . . . . . .
 2  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 1  . . . . . . . . . . . . .     . . . . . . . . . . . . .
    A B C D E F G H J K L M N 


= 

play white pass 
Move: 2     Black: 0 caps   White: 0 caps   Komi: 7.5
 13 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 12 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 11 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 10 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 9  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 8  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 7  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 6  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 5  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 4  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 3  . . X . . . . . . . . . .     . . . . . . . . . . . . .
 2  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 1  . . . . . . . . . . . . .     . . . . . . . . . . . . .
    A B C D E F G H J K L M N 


= 

play block c11
Move: 3     Black: 0 caps   White: 0 caps   Komi: 7.5
 13 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 12 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 11 . .(X). . . . . . . . . .     . . . . . . . . . . . . .
 10 . . . . . . . . . . . . .     . . . . . . . . . . . . .
 9  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 8  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 7  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 6  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 5  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 4  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 3  . . X . . . . . . . . . .     . . . . . . . . . . . . .
 2  . . . . . . . . . . . . .     . . . . . . . . . . . . .
 1  . . . . . . . . . . . . .     . . . . . . . . . . . . .
    A B C D E F G H J K L M N 

```

It'd be nice to have an `add black c3` command before the first move is made (when `pos->n` is still 0). It is very useful for setting up life and death go problems.

**Comment by db3108** [comment]
You can use the command :

debug setpos C3 pass C11

Notes :
1. The command can be repeated for setting a position with many stones
2. I have made a modification on GitHub in order that the pass is not 
ignored
    -> so you should get the latest version to use it

I am sorry, but I have to leave now and I won't be able to read and post 
messages until next Monday.

Enjoy!

Denis

**Comment by db3108** [comment]
You can use the following command

debug setpos C3 pass C11

Notes.
1. The command can be repeated anytime if you net to setup a lot of stones
2. I had to make a small modification to the program for the pass to be 
taken into
    account. So you should reload the project and build the executable 
again to use   it.

PS. Sorry, but I must leave now and won't be able to read or post 
messages until next monday.

Enjoy!

Best,
Denis

**Comment by horaceho** [comment]
`debug setpos ...` works fine for me. I am wondering whether there is any side effect if I do a:

`pos->n = 0;`

after `debug setpos`? What I am try to do is to support `addblack` and `addwhite` functions similar to the [`ab` and `aw`](http://www.red-bean.com/sgf/properties.html#AB) in sgf, which are only allowed before a game starts (i.e.: n == 0).

**Comment by db3108** [comment]
Hi Horace,

I don't see obvious side effect.

However, I think that what you are trying to do should be done after the 
fast board is coded. Indeed, I will need to change the representation of 
the Position.

At least, as I mentionned in the mail to the computer go mailing list 
and in the README of michi-c, I believed that these modifications should 
not be done in the project michi-c but in the project michi-c2 (in order 
to keep michi-c as simple as possible for beginners). Your modifications 
may be simple, but there are a multitude of other things that must be added.

One question, for my curiosity ... Why did you need to add a main.c ? Is 
this mandatory for XCode ?

Best,
Denis

**Comment by horaceho** [comment]
iOS app comes with its own main() and will conflict with michi.c when linked together. The new main.c is excluded from a Xcode project but keeps working in non-iOS environment. 

IMHO, I'd prefer new changes to be made in the same github project so we can see and learn how michi evolves. If you'd like to preserve a michi.py-like version, a "classic" tag will do. 

Just my two cents.

**Comment by horaceho** [comment]
It's great to know there is a fast board being built and Position will be updated. I hope that you may consider a few enhancements:
- don't ignore color in `play` command, as alternate play not being forced
- add  a `who` attribute to indicate who to play the next move for current pos, instead of deduced from `n` the move number
- hopefully a `size` attribute to setup a pos to different board sizes (9, 13, 19 may be sufficient), say, a 19x19  (N = 19) board could be used for 19x19, 13x13, or 9x9 games
- `RESIGN_THRES` as a valuable instead of constant

Thanks!

**Comment by db3108** [comment]
Horace,

I understand your point. However, it does not make me change my mind.

You should not forget that one primary goal of michi is to provide 
beginners with a strong but simple and clear implementation of a go 
engine that is less intimidating to read than other more powerful go 
programs like pachi, fuego or others.

Therefore, I don't like the idea that a beginner must know or learn how 
to use git before to get access to the simpler original implementation. 
This one should be the first that he sees.

For the most experienced programmers this will not be a problem to 
explore the development branch michi-c2 that will record how michi 
evolves (as the start of the project is a clone of michi-c and michi-c 
will not evolve except for bug corrections).

Thank you for your thoughts.

Best,
Denis

**Comment by horaceho** [comment]
Thanks! I'll keep an eye on michi-c2 ;-)
