### ISSUE TITLE
error messages in regression tests by "$ make test"

### ISSUE THREAD

**Issue by j-kartz** [db3108/michi-c#3]
Great project.  Thank you.

You wrote in README.md:

> $ make test
> :
> 
> > The Go program terminated unexpectedly.
> > make: **\* [test] Error 2
> > Do not be bothered by the error message at the end of the 2 tests ...
> > If someone can explain and solve the problem, ...

I think you need to add the printf() below to send the final GTP response:

```
  [michi.c]
  1409     else if (strcmp(command,"quit") == 0) {
  1410         log_hashtable_synthesis();
               printf("=%s \n\n", cmdid);    // <==
  1411         break;
  1412     }
```

The error messages have disappeared.

**Comment by db3108** [comment]
Thank you very much,

The modification is done on GitHub.

Denis
