### ISSUE TITLE
uint type not totally portable

### ISSUE THREAD

**Issue by eriksteinmetz** [db3108/michi-c#4]
If you replace the four occurrences of uint with unsigned int, the code will become more portable. For example, it did not compile out of the box on Mac OS X, since there is not a 'typedef unsigned int uint' in the normal build system under the current OS X.
With replacement it compiles on OS X, and also compiles on (at least Ubuntu and Arch) Linux.
Thanks!
Erik

**Comment by db3108** [comment]
Hi Eric,

Thank you. Correction done (by Horace Ho).

Best,
Denis
